[da-vinci-client] Do not attempt to restore meta system store on DaVinciBackend initialization (#413)
Users that have ran DaVinci based metadata or store repository will run into the following exception:
java.lang.UnsupportedOperationException: The implementation ThinClientMetaStoreBasedRepository
should not be subscribing to system store...
when they try to run DaVinci client with thin client based store repository. This is because DaVinci
backend will try to restore all on disk stores upon initialization, including meta system stores.
User would then have to perform manual cleanup in the data.base.path in order to proceed.

1. Added logic to skip restoring meta system stores so they will only be subscribed explictly when
needed.

2. Added an integration test with static data.base.path to reproduce the exact problem.

(cherry picked from commit abfb91a83cc2c3096c4bdc7df3b8fed6ab7af58c)